## templates/service.yaml

  {{- if .Values.prometheus.enabled -}}
apiVersion: v2
kind: Service
metadata:
  name: prometheus
  labels:
    app: prometheus
spec:
  type: NodePort
  selector:
    app: prometheus
  ports:
    - port: 9090
      targetPort: 9090
      nodePort: 30000
  {{- end -}}

  {{- if .Values.grafana.enabled -}}
apiVersion: v2
kind: Service
metadata:
  name: grafana
  labels:
    app: grafana
spec:
  type: NodePort
  selector:
    app: grafana
  ports:
    - port: 80
      targetPort: 3000
      nodePort: 30001
  {{- end -}}
